on: 
  workflow_call:
    secrets:
      GITHUB_TOKEN_USER:
        required: true
    
name: üè∑Ô∏è Add or update labels to PRs

jobs:
  add-label:
    runs-on: ubuntu-latest

    env:
      LABEL: ""

    permissions:
      packages: write
      contents: write
      pull-requests: write
      repository-projects: read

    name: üè∑Ô∏è Add or update labels to PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check branch name and determine label
        run: |
          PR_URL="${{ github.event.pull_request.html_url }}"
          BRANCH_NAME="${{ github.head_ref }}"
          if [[ $BRANCH_NAME == chore/* ]]; then
            LABEL="chore :construction_worker_man:"
          elif [[ $BRANCH_NAME == feat/* ]]; then
            LABEL="enhancement :sparkles:"
          elif [[ $BRANCH_NAME == fix/* ]]; then
            LABEL="bug :bug:"
          else
            LABEL="other :question:"
          fi
          echo "Label to be added/updated: $LABEL"
          echo "LABEL=$LABEL" >> $GITHUB_ENV
        id: set-label

      - name: üè∑Ô∏è Add or Update Label
        run: | 
          gh pr edit ${{ github.event.pull_request.number }} --add-label "${{ env.LABEL }}"
          gh pr comment ${{ github.event.pull_request.number }} --body "This PR has been labeled as ${{ env.LABEL }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_USER }}